### PR TITLE
update Stack resolver to GHC 8.10

### PR DESCRIPTION
**Pull request by peterbecich**
Both Stack and Cabal build with GHC 8.10 successfully:

```
% stack test --no-run-tests     
avaleryar> Test running disabled by --no-run-tests flag.

% ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4

% cabal build --enable-tests all
Up to date
```

### CODE REVIEW

**Comment by deviant-logic** [comment]
Hey Peter---would it inconvenience you if I held off on merging this for a few days because I anticipate some changes to dependencies, and then we'd have to do this all over again?

**Comment by peterbecich** [comment]
sounds good, thx

**Comment by peterbecich** [comment]
This generated line has not been updated:
https://github.com/simspace/avaleryar/blob/ed1490412406e1e3304bc9d34199150c50f072ea/extras/avaleryar-extras.cabal#L10

**Review by alec-simspace — DISMISSED** [review]
Looks reasonable to me.

**Review by alec-simspace — DISMISSED** [review]

**Comment by peterbecich** [comment]
LGTM

**Review by jship — APPROVED** [review]

**Pull request merged**
